[package]
name = "StellarHash"
version = "0.1.0"
edition = "2024"

[dependencies]

bevy = "0.14"

criterion = "0.5"

[profile.release]
opt-level = 3
lto = "thin"

[[bench]]
name = "generationHashageBench"
harness = false

[[bench]]
name = "garbageCollectorBench"
harness = false

[[bench]]
name = "astrophysiqueBench"
harness = false

[[bench]]
name = "uiSurvolBench"
harness = false

[[bench]]
name = "orbitesBench"
harness = false