name: Generate Changelog.md

on:
  push:
    branches:
      - main
    # The CHANGELOG.md file is ignored to avoid an infinite loop.
    paths-ignore:
      - 'CHANGELOG.md'

jobs:
  changelog:
    runs-on: ubuntu-latest
    permissions:
      # Allows the GitHub bot to make a commit
      contents: write 
      pull-requests: write

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
        with:
          # Essential for git-cliff to read the entire history.
          fetch-depth: 0

      - name: Génération du Changelog
        uses: orhun/git-cliff-action@v4
        with:
          args: -o CHANGELOG.md
        env:
          OUTPUT: CHANGELOG.md
          
      - name: 📤 Créer une Pull Request pour le Changelog
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(changelog): mise à jour du CHANGELOG"
          title: "Mise à jour automatique du Changelog"
          branch: "chore/update-changelog"
          body: "Cette PR a été générée automatiquement par git-cliff."
